import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google"; 
import Navbar from "./components/navbar/Navbar";


export const metadata: Metadata = {
  title: "HMS",
  description: "Generated by create next app",
};

const font = Nunito({
  subsets: ["latin"],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
