import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google"; 
import Navbar from "./components/navbar/Navbar";
import RegisterModel from "./components/models/RegisterModel";
import ToasterProvider from "./providers/ToasterProvider";
import LoginModel from "./components/models/LoginModel";
import getCurrentUser from "./actions/getCurrentUser";
import RentModel from "./components/models/RentModel";
import ClientOnly from "./components/ClientOnly";
import SearchModel from "./components/models/SearchModel";


export const metadata: Metadata = {
  title: "HMS",
  description: "Generated by create next app",
};

const font = Nunito({
  subsets: ["latin"],
})

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

   const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <head>
      <link rel="icon" href="@/app/logo.jpg" />
      </head>
      <body className={font.className}>
        {/* <Model isOpen actionLabel="Submit" /> */}
        <ClientOnly>
        <ToasterProvider />
        <SearchModel />
        <RentModel />
        <LoginModel />
        <RegisterModel />
        <Navbar currentUser = {currentUser} />
        </ClientOnly>
        <div className="pb-20 pt-28">
           {children}
        </div>
        </body>
    </html>
  );
}
